version: '3'
services:
      app:
            build:
                  context: ./
            
      nginx:
            image: nginx:latest
            volumes:
                  - ./nginx.conf:/etc/nginx/conf.d/default.conf
                  - /home/ubuntu/privkey.pem:/privkey.pem # mount the ssl private key 
                  - /home/ubuntu/fullchain.pem:/fullchain.pem # mount the ssl cert key 
            depends_on:
                  - app
            ports:
                  - "80:80"
                  - "443:443"






